### ISSUE TITLE
Autodiscovery

### ISSUE THREAD

**Issue by Mwalton4uk** [hass-agent/HASS.Agent-Integration#10]
HA Intergration won't auto-discover my PC and when I attempt the legacy method it also fails.

Its working with MQTT and full functional otherwise, just the integration wont work so I can't use the media function. 

If I try the legacy feature, this is the present error:

```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 12:09:10 pm (1 occurrences)
Last logged: 12:09:10 pm

Error setting up entry MORGAN-PC for hass_agent
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hass_agent/__init__.py", line 135, in async_setup_entry
    _logger.debug("setting up device from config entry: %s [%s]", entry.data["device"]["name"], entry.unique_id)
                                                                  ~~~~~~~~~~^^^^^^^^^^
KeyError: 'device'
```

**Comment by thewolfman56** [comment]
I'm having the same issue when I added hass.agent 2 to a new PC.  Integration will not auto discover and manual method isn't working either, but MQTT connects.  Did you fix yours?

**Comment by Bastian007** [comment]
I can confirm the same behaviour, with 2nd device no auto-dicovery.
Is there any possibility to add it manually without using local API?
