### ISSUE TITLE
I can't connect a second computer to the media player entity. Home Assistant just won't find my device

### ISSUE THREAD

**Issue by FLab-Projects** [hass-agent/HASS.Agent-Integration#12]
I have two computers at home: mine and my girlfriend's. I'm trying to connect two computers with separate media players for each of them.
One of their computers works perfectly the first time. Home Assistant automatically detects my computer, just as it's designed to do. When I try to connect a second computer, Home Assistant simply does not find the device. With MQTT everything works as it should, but the media player entity is not created automatically.

Perhaps I'm doing something wrong. I would be grateful for any advice :)

UPD. With the update to HASS 2024.10.0, the problem went away, immediately after the update - the second computer was found as a new device. Now the problem is different. The media player of the first computer works fine, but the second one is in the "Unavailable" status. Restarting the integration, deleting and re-adding the device does not help.
I checked the HASS Agent settings on both computers, they are identical And the computer media player that I connect second is always "Unavailable". 

Home Assistant Agent version 2.1.0

**Comment by suprra** [comment]
I found to add more computers on a network, gotta remove the integration and install it again.  Then it picks them all up, gotta keep doing this every time you add another pc but it's just a couple of clicks really.
