### ISSUE TITLE
Media Player volume control doesn't function

### ISSUE THREAD

**Issue by lichenophile** [hass-agent/HASS.Agent-Integration#6]
Increase and decrease volume within the media player entity work fine. 

However the slider for the media player produces no result.

I've removed the integration and readded it, which didn't fix the issue either.

Creating a button through hass-agent to set volume level (using a default value) works fine also, but I haven't managed to test publishing a custom value as I'm unsure of the syntax for the `payload` field (I tried "50" but no dice)

**Comment by amadeo-alex** [comment]
Hello, this might be related more to HASS.Agent itself but in case this is decided we can move the issue.
What version of HASS.Agent and the integration are you using?
Are there any logs present after the failed attempt to set the volume? (with extended logging enabled)?
