### ISSUE TITLE
Home Assistant Core Warning

### ISSUE THREAD

**Issue by DanielHoelder** [hass-agent/HASS.Agent-Integration#9]
Hi,
I got a warning message in the Home Assistant Core. The message asks to report it to the author of HASS.agent.

I didn't experience a problem with HASS.agent yet. But I'm still exploring it. 

That's the warning message:

"Detected that custom integration 'hass_agent' calls device_registry.async_update_device from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#device_registryasync_update_device at custom_components/hass_agent/__init__.py, line 29: device_registry.async_get_or_create(, please report it to the author of the 'hass_agent' custom integration"

**Comment by DrR0X-glitch** [comment]
Moved to correct repo, if you follow instructions at https://www.hass-agent.io/2.1/getting-started/installation/#installing-the-home-assistant-integration or in the README of this repo this issue should be fixed. You are using the old integration, uninstall it and switch to this one.

**Comment by DanielHoelder** [comment]
Thank you!
